model: D:/jupyter_notebook/yolov5-master/yolov5-master/runs/train-cls/exp17/weights/best.pt
data: D:/jupyter_notebook/yolov5-master/datasets/RSCD dataset-1million
epochs: 20
batch_size: 64
imgsz: 224
nosave: false
cache: null
device: ''
workers: 0
project: ..\runs\train-cls
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: ..\runs\train-cls\exp18
